/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Список предстоящих броней всех типов (владелец), сортировка по времени */
        get: operations["Bookings_list"];
        put?: never;
        /** @description Создать бронь на свободный слот (гость) */
        post: operations["Bookings_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Отменить бронь (владелец) */
        delete: operations["Bookings_cancel"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Список типов событий (гость и владелец) */
        get: operations["EventTypes_list"];
        put?: never;
        /** @description Создать тип события (владелец) */
        post: operations["EventTypes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Получить тип события по идентификатору */
        get: operations["EventTypes_read"];
        put?: never;
        post?: never;
        /** @description Удалить тип события (владелец). 409, если есть предстоящие брони */
        delete: operations["EventTypes_delete"];
        options?: never;
        head?: never;
        /** @description Частично обновить тип события (владелец) */
        patch: operations["EventTypes_update"];
        trace?: never;
    };
    "/event-types/{id}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Слоты типа события на 14 дней вперёд со статусом free/busy */
        get: operations["EventTypes_slots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Проверка живости сервиса */
        get: operations["HealthRoutes_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/owner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Публичный профиль владельца календаря */
        get: operations["OwnerRoutes_read"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Единое тело ошибки */
        ApiError: {
            /** @description Машиночитаемый код, например slot_busy, out_of_window, event_type_not_found */
            code: string;
            /** @description Человекочитаемое сообщение */
            message: string;
        };
        /** @description Бронирование встречи */
        Booking: {
            /**
             * Format: int64
             * @description Идентификатор
             */
            id: number;
            /**
             * Format: int64
             * @description Идентификатор типа события
             */
            eventTypeId: number;
            /** @description Название типа события на момент брони */
            eventTypeTitle: string;
            /**
             * Format: int32
             * @description Длительность типа события в минутах
             */
            durationMinutes: number;
            /**
             * Format: date-time
             * @description Начало встречи
             */
            start: string;
            /**
             * Format: date-time
             * @description Конец встречи (вычисляется сервером из длительности)
             */
            end: string;
            /** @description Имя гостя */
            guestName: string;
            /** @description Email гостя */
            guestEmail: string;
            /** @description Заметка/тема встречи */
            note?: string;
            /**
             * Format: date-time
             * @description Момент создания брони
             */
            createdAt: string;
        };
        /** @description Данные для создания брони гостем */
        BookingCreate: {
            /**
             * Format: int64
             * @description Идентификатор выбранного типа события
             */
            eventTypeId: number;
            /**
             * Format: date-time
             * @description Начало выбранного слота
             */
            start: string;
            guestName: string;
            /** Format: email */
            guestEmail: string;
            note?: string;
        };
        /** @description Тип события, создаётся владельцем календаря */
        EventType: {
            /**
             * Format: int64
             * @description Идентификатор
             */
            id: number;
            /** @description Название */
            title: string;
            /** @description Описание */
            description: string;
            /**
             * Format: int32
             * @description Длительность в минутах (1..480)
             */
            durationMinutes: number;
        };
        /** @description Данные для создания типа события */
        EventTypeCreate: {
            title: string;
            description: string;
            /** Format: int32 */
            durationMinutes: number;
        };
        /** @description Данные для частичного обновления типа события */
        EventTypeUpdate: {
            title?: string;
            description?: string;
            /** Format: int32 */
            durationMinutes?: number;
        };
        /** @description Состояние сервиса */
        HealthStatus: {
            status: string;
        };
        /** @description Публичный профиль владельца календаря */
        Owner: {
            /** @description Имя владельца */
            name: string;
            /** @description Подзаголовок/роль, например Host */
            title: string;
            /** @description Описание */
            description: string;
        };
        /** @description Временной слот для типа события. Шаг сетки равен длительности типа. */
        Slot: {
            /**
             * Format: date-time
             * @description Начало слота (TZ владельца, +03:00)
             */
            start: string;
            /**
             * Format: date-time
             * @description Конец слота
             */
            end: string;
            /** @description Свободен или занят */
            status: components["schemas"]["SlotStatus"];
        };
        /**
         * @description Статус слота
         * @enum {string}
         */
        SlotStatus: "free" | "busy";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Bookings_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"][];
                };
            };
        };
    };
    Bookings_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description Ресурс не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Конфликт: время занято или удаление невозможно */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Ошибка валидации: слот вне окна/часов или некорректные данные */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    Bookings_cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Ресурс не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    EventTypes_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"][];
                };
            };
        };
    };
    EventTypes_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventTypeCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description Ошибка валидации: слот вне окна/часов или некорректные данные */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    EventTypes_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description Ресурс не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    EventTypes_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Ресурс не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Конфликт: время занято или удаление невозможно */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    EventTypes_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventTypeUpdate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description Ресурс не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Ошибка валидации: слот вне окна/часов или некорректные данные */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    EventTypes_slots: {
        parameters: {
            query?: {
                /** @description Начало диапазона (по умолчанию текущая дата) */
                from?: string;
                /** @description Конец диапазона (по умолчанию текущая дата + 14 дней) */
                to?: string;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Slot"][];
                };
            };
            /** @description Ресурс не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    HealthRoutes_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    OwnerRoutes_read: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Owner"];
                };
            };
        };
    };
}
